### ISSUE TITLE
erreur lors de changement de propriétaire

### ISSUE THREAD

**Issue by Monaa** [davout/equibook#3]
modification propriétaire dans l’écran d’édition du cheval (titeuf) pour mettre fanny herbert. meme erreur par l’écran utilisateur en ajoutant un cheval existant
message : 
![capture d ecran 2015-12-17 a 12 33 37](https://cloud.githubusercontent.com/assets/430091/11883459/608586ee-a513-11e5-9feb-9be5ef71f9d8.png)

la première fois via l’écran d’édition du cheval ça n’a pas fonctionné
la deuxième fois via l’utilisateur, le cheval a été ajouté

**Comment by davout** [comment]
Je ne reproduis plus en production.

**Comment by Monaa** [comment]
moi non plus
