### ISSUE TITLE
bug/évolution pouvoir modifier un cheval 

### ISSUE THREAD

**Issue by Monaa** [davout/equibook#5]
pouvoir modifier un cheval dans la liste des chevaux de l'utilisateur : 
![capture d ecran 2015-12-18 a 17 01 20](https://cloud.githubusercontent.com/assets/430091/11900951/2373ea2a-a5a9-11e5-90dd-1bcb8f15c11f.png)

pour l'instant on le fait via l'admin

**Comment by Monaa** [comment]
heu ... on peut pas tous les modifier : 

![capture d ecran 2015-12-22 a 23 33 27](https://cloud.githubusercontent.com/assets/430091/11967614/9057e14c-a904-11e5-95d0-f84faf91063e.png)

**Comment by davout** [comment]
On peut modifier ceux dont on est propriétaire.

**Comment by Monaa** [comment]
ok
