### ISSUE TITLE
erreur lors du chargement d'une image sur un cheval

### ISSUE THREAD

**Issue by Monaa** [davout/equibook#9]
![capture d ecran 2015-12-22 a 23 41 45](https://cloud.githubusercontent.com/assets/430091/11967739/a2724614-a905-11e5-9dbb-0103abdfdf52.png)

**Comment by davout** [comment]
Ouais j'ai vu ça, j'ai mis mes équipes dessus.

**Comment by Monaa** [comment]
<3
